python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.0
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.1
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.2
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.3
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.4
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.5
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.6
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.7
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.8
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.9
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.05
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.15
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.25
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.35
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.45
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.55
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.65
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.75
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.85
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 o 0.95
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.0
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.1
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.2
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.3
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.4
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.5
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.6
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.7
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.8
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.9
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.05
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.15
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.25
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.35
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.45
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.55
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.65
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.75
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.85
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 r 0.95
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.0
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.1
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.2
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.3
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.4
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.5
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.6
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.7
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.8
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.9
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.05
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.15
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.25
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.35
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.45
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.55
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.65
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.75
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.85
python aumic_phase_analysis_adtest_doubletriplesample.py 0 1 b 0.95

